import Head from 'next/head';
import Link from 'next/link';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Flipcaet' : 'Flipcart'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 item-center px-4 justify-between  shadow-md">
            <Link legacyBehavior href="/">
              <a className="text-lg font-bold">Flipcart</a>
            </Link>
            <div>
              <Link legacyBehavior href="/">
                <a className="p-2">Cart</a>
              </Link>
              <Link legacyBehavior href="/">
                <a className="p-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright @ 2023 Flipcart</p>
        </footer>
      </div>
    </>
  );
}
