const data = {
  products: [
    {
      name: 'Short Frock',
      slug: 'short-frock',
      category: 'frocks',
      image: '/images/shortfrock.jpg',
      price: 100,
      brans: 'H&M',
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Frock',
    },
    {
      name: 'Long Frock',
      slug: 'long-frock',
      category: 'frocks',
      image: '/images/longfrock.jpg',
      price: 120,
      brans: 'H&M',
      rating: 5,
      numReviews: 10,
      countInStock: 10,
      description: 'A popular Frock',
    },
    {
      name: 'Pencil Pant',
      slug: 'pencil-pant',
      category: 'pant',
      image: '/images/jeans.jpg',
      price: 150,
      brans: 'Nike',
      rating: 4,
      numReviews: 8,
      countInStock: 10,
      description: 'A Jeans pant',
    },
    {
      name: 'Shorts',
      slug: 'shorts',
      category: 'shorts',
      image: '/images/shorts.jpg',
      price: 150,
      brans: 'Max',
      rating: 5,
      numReviews: 8,
      countInStock: 8,
      description: 'A popular shorts',
    },
    {
      name: 'Crop T Shirt',
      slug: 'crop-t-shirt',
      category: 'shirts',
      image: '/images/croptop.jpg',
      price: 100,
      brans: 'Nike',
      rating: 5,
      numReviews: 8,
      countInStock: 15,
      description: 'A popular jeans shirt',
    },
    {
      name: 'Top',
      slug: 'top',
      category: 'shirts',
      image: '/images/top.jpg',
      price: 100,
      brans: 'Max',
      rating: 5,
      numReviews: 8,
      countInStock: 15,
      description: 'A popular Jeans top',
    },
  ],
};

export default data;
